/* ParserHDDL.java */
/* Generated By:JavaCC: Do not edit this line. ParserHDDL.java */
  package com.kazimirm.hddlParser.parser;

  import java.io.*;
  import java.util.*;
  import com.kazimirm.hddlParser.hddlObjects.*;

  public class ParserHDDL implements ParserHDDLConstants {

    public static void main(String[] args) throws ParseException,FileNotFoundException {

       if (args.length < 1) {
           System.out.println("Please pass in the filename for a parameter.");
           System.exit(1);
       }

        ParserHDDL parser = new ParserHDDL(new FileInputStream(args[0]));

        Domain domain = parser.start();
        System.out.println("Parse completed.");
     }

////////////////////////////////////////////////////////////////////////
////////////////    ENTRY POINT      ///////////////////////////////////
////////////////////////////////////////////////////////////////////////
  static final public 
  Domain start() throws ParseException {Domain domain = new Domain();
//      Problem problem = new Problem();

    domain = domain();
    jj_consume_token(0);
{if ("" != null) return domain;}
    throw new Error("Missing return statement in function");
}

////////////////////////////////////////////////////////////////////////
////////////////    HELP METHODS       /////////////////////////////////
////////////////////////////////////////////////////////////////////////
  static final public   String getAttribute() throws ParseException {Token attribute;
    attribute = jj_consume_token(VAR);
{if ("" != null) return attribute.toString();}
    throw new Error("Missing return statement in function");
}

////////////////////////////////////////////////////////////////////////
////////////////    DOMAIN      ////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
  static final public 
  Domain domain() throws ParseException {Domain domain = new Domain();
    List<Requirement> requirements = new ArrayList<>();
    List<Type> types = new ArrayList<>();
    List<Predicate> predicates = new ArrayList<>();
    List<Task> tasks = new ArrayList<>();
    List<Method> methods = new ArrayList<>();
    String domainName;
    jj_consume_token(LPAR);
    jj_consume_token(DEFINE);
    jj_consume_token(LPAR);
    jj_consume_token(DOMAIN);
    domainName = getAttribute();
    jj_consume_token(RPAR);
    requirements = getRequirements();
    types = getTypes();
    predicates = getPredicates();
    tasks = getTasks();
    methods = getMethods();
domain.setName(domainName);
        domain.setRequirements(requirements);
        domain.setTypes(types);
        domain.setPredicates(predicates);
        domain.setTasks(tasks);
        domain.setMethods(methods);
        {if ("" != null) return domain;}
    throw new Error("Missing return statement in function");
}

////////////////////////////////////////////////////////////////////////
////////////////    REQUIREMENTS       /////////////////////////////////
////////////////////////////////////////////////////////////////////////
  static final public 
List<Requirement> getRequirements() throws ParseException {List<Requirement> requirements = new ArrayList<>();
    Requirement requirement;
    jj_consume_token(LPAR);
    jj_consume_token(COLON);
    jj_consume_token(REQUIREMENTS);
    label_1:
    while (true) {
      if (jj_2_1(3)) {
        ;
      } else {
        break label_1;
      }
      requirement = getRequirement();
requirements.add(requirement);
    }
    jj_consume_token(RPAR);
{if ("" != null) return requirements;}
    throw new Error("Missing return statement in function");
}

  static final public Requirement getRequirement() throws ParseException {Requirement requirement = new Requirement();
     String value;
    jj_consume_token(COLON);
    value = getAttribute();
requirement.setValue(value);
        {if ("" != null) return requirement;}
    throw new Error("Missing return statement in function");
}

////////////////////////////////////////////////////////////////////////
////////////////    TYPES   ////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
  static final public 
 List<Type> getTypes() throws ParseException {List<Type> types = new ArrayList<>();
    Type type;
    jj_consume_token(LPAR);
    jj_consume_token(COLON);
    jj_consume_token(TYPES);
    label_2:
    while (true) {
      if (jj_2_2(3)) {
        ;
      } else {
        break label_2;
      }
      type = getType();
types.add(type);
    }
    jj_consume_token(RPAR);
{if ("" != null) return types;}
    throw new Error("Missing return statement in function");
}

  static final public Type getType() throws ParseException {Type type = new Type();
     String name;
     String baseType;
    name = getAttribute();
    jj_consume_token(DASH);
    baseType = getAttribute();
type.setName(name);
        type.setBaseType(baseType);
        {if ("" != null) return type;}
    throw new Error("Missing return statement in function");
}

////////////////////////////////////////////////////////////////////////
////////////////    PREDICATES   ///////////////////////////////////////
////////////////////////////////////////////////////////////////////////
  static final public 
  List<Predicate> getPredicates() throws ParseException {List<Predicate> predicates = new ArrayList<>();
     Predicate predicate;
    jj_consume_token(LPAR);
    jj_consume_token(COLON);
    jj_consume_token(PREDICATES);
    label_3:
    while (true) {
      if (jj_2_3(3)) {
        ;
      } else {
        break label_3;
      }
      predicate = getPredicate();
predicates.add(predicate);
    }
    jj_consume_token(RPAR);
{if ("" != null) return predicates;}
    throw new Error("Missing return statement in function");
}

  static final public Predicate getPredicate() throws ParseException {Predicate predicate = new Predicate();
     List<Argument> arguments = new ArrayList<>();
     Argument argument = new Argument();
     String name;
     String argumentName;
     String argumentType;
    jj_consume_token(LPAR);
    name = getAttribute();
    label_4:
    while (true) {
      jj_consume_token(QUESTIONMARK);
      argumentName = getAttribute();
      jj_consume_token(DASH);
      argumentType = getAttribute();
argument.setName(argumentName);
                            argument.setType(argumentType);
                            arguments.add(argument);
      if (jj_2_4(3)) {
        ;
      } else {
        break label_4;
      }
    }
    jj_consume_token(RPAR);
predicate.setName(name);
        predicate.setArguments(arguments);
        {if ("" != null) return predicate;}
    throw new Error("Missing return statement in function");
}

////////////////////////////////////////////////////////////////////////
////////////////    GET PARAMETERS   ///////////////////////////////////
////////////////////////////////////////////////////////////////////////
///                 Used in task/method body                         ///
////////////////////////////////////////////////////////////////////////
  static final public 
List<Parameter> getParameters() throws ParseException {List<Parameter> parameters = new ArrayList<>();
    String paramName;
    String paramType;
    jj_consume_token(COLON);
    jj_consume_token(PARAMETERS);
    jj_consume_token(LPAR);
    label_5:
    while (true) {
      if (jj_2_5(3)) {
        ;
      } else {
        break label_5;
      }
      jj_consume_token(QUESTIONMARK);
      paramName = getAttribute();
      jj_consume_token(DASH);
      paramType = getAttribute();
Parameter parameter = new Parameter();
             parameter.setName(paramName);
             parameter.setType(paramType);
             parameters.add(parameter);
    }
    jj_consume_token(RPAR);
{if ("" != null) return parameters;}
    throw new Error("Missing return statement in function");
}

////////////////////////////////////////////////////////////////////////
////////////////    TASKS   ////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
  static final public 
Task getTask() throws ParseException {Task task = new Task();
    List<Parameter> parameters = new ArrayList<>();
    String name;
    String paramName;
    String paramType;
    name = getAttribute();
    parameters = getParameters();
task.setName(name);
        task.setParameters(parameters);
        {if ("" != null) return task;}
    throw new Error("Missing return statement in function");
}

  static final public List<Task> getTasks() throws ParseException {List<Task> tasks = new ArrayList<>();
     List<Argument> arguments = new ArrayList<>();
     String name;
    label_6:
    while (true) {
      if (jj_2_6(3)) {
        ;
      } else {
        break label_6;
      }
Task task = new Task();
      jj_consume_token(LPAR);
      jj_consume_token(COLON);
      jj_consume_token(TASK);
      task = getTask();
      jj_consume_token(RPAR);
tasks.add(task);
    }
{if ("" != null) return tasks;}
    throw new Error("Missing return statement in function");
}

////////////////////////////////////////////////////////////////////////
////////////////    METHODS   //////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
  static final public List<Method> getMethods() throws ParseException {List<Method> methods = new ArrayList<>();
    Method method;
    label_7:
    while (true) {
      if (jj_2_7(3)) {
        ;
      } else {
        break label_7;
      }
      jj_consume_token(LPAR);
      jj_consume_token(COLON);
      jj_consume_token(METHOD);
      method = getMethod();
methods.add(method);
    }
{if ("" != null) return methods;}
    throw new Error("Missing return statement in function");
}

  static final public Method getMethod() throws ParseException {Method method = new Method();
    Task task = new Task();
    List<Parameter> methodParameters = new ArrayList<>();
    List<Subtask> subtasks = new ArrayList<>();
    String methodName;
    String paramName;
    String paramType;
    String taskName;
    methodName = getAttribute();
    methodParameters = getParameters();
    task = getTaskSignature(methodParameters);
    subtasks = getSubtasks();
method.setName(methodName);
        method.setTask(task);
        method.setSubtasks(subtasks);
        {if ("" != null) return method;}
    throw new Error("Missing return statement in function");
}

  static final public Task getTaskSignature(List<Parameter> parameters) throws ParseException {Task task = new Task();
     List<Parameter> taskParameters = new ArrayList<>();
     String taskName;
     String paramName;
    jj_consume_token(COLON);
    jj_consume_token(TASK);
    jj_consume_token(LPAR);
    taskName = getAttribute();
    label_8:
    while (true) {
      if (jj_2_8(3)) {
        ;
      } else {
        break label_8;
      }
      jj_consume_token(QUESTIONMARK);
      paramName = getAttribute();
for(Parameter p : parameters) {
            if(p.getName().equals(paramName)) {
                taskParameters.add(p);
            }
        }
    }
    jj_consume_token(RPAR);
task.setName(taskName);
        task.setParameters(taskParameters);
        {if ("" != null) return task;}
    throw new Error("Missing return statement in function");
}

  static final public List<Subtask> getSubtasks() throws ParseException {List<Subtask> subtasks = new ArrayList<>();
    List<Parameter> subtaskParameters = new ArrayList<>();
    String subtaskName;
    String taskName;
    String param;
    jj_consume_token(COLON);
    jj_consume_token(SUBTASKS);
    jj_consume_token(LPAR);
    jj_consume_token(AND);
    jj_consume_token(LPAR);
    subtaskName = getAttribute();
    jj_consume_token(LPAR);
    taskName = getAttribute();
    label_9:
    while (true) {
      if (jj_2_9(3)) {
        ;
      } else {
        break label_9;
      }
      jj_consume_token(QUESTIONMARK);
      param = getAttribute();
Parameter parameter = new Parameter();
                        parameter.setName(taskName);
                        subtaskParameters.add(parameter);
    }
    jj_consume_token(RPAR);
    jj_consume_token(RPAR);
Subtask subtask = new Subtask();
            Task task = new Task();
            subtask.setName(subtaskName);
            task.setName(taskName);
            task.setParameters(subtaskParameters);
            subtask.setTask(task);
            subtasks.add(subtask);
    jj_consume_token(RPAR);
{if ("" != null) return subtasks;}
    throw new Error("Missing return statement in function");
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_9()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_3R_getRequirement_154_6_10()
 {
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_getAttribute_96_5_13()) return true;
    return false;
  }

  static private boolean jj_3R_getPredicate_221_6_12()
 {
    if (jj_scan_token(LPAR)) return true;
    if (jj_3R_getAttribute_96_5_13()) return true;
    Token xsp;
    if (jj_3_4()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_4()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_getRequirement_154_6_10()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_getType_184_6_11()) return true;
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_scan_token(QUESTIONMARK)) return true;
    if (jj_3R_getAttribute_96_5_13()) return true;
    if (jj_scan_token(DASH)) return true;
    return false;
  }

  static private boolean jj_3_9()
 {
    if (jj_scan_token(QUESTIONMARK)) return true;
    if (jj_3R_getAttribute_96_5_13()) return true;
    return false;
  }

  static private boolean jj_3R_getAttribute_96_5_13()
 {
    if (jj_scan_token(VAR)) return true;
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_scan_token(QUESTIONMARK)) return true;
    if (jj_3R_getAttribute_96_5_13()) return true;
    if (jj_scan_token(DASH)) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_3R_getPredicate_221_6_12()) return true;
    return false;
  }

  static private boolean jj_3R_getType_184_6_11()
 {
    if (jj_3R_getAttribute_96_5_13()) return true;
    if (jj_scan_token(DASH)) return true;
    if (jj_3R_getAttribute_96_5_13()) return true;
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_scan_token(LPAR)) return true;
    if (jj_scan_token(COLON)) return true;
    if (jj_scan_token(TASK)) return true;
    return false;
  }

  static private boolean jj_3_7()
 {
    if (jj_scan_token(LPAR)) return true;
    if (jj_scan_token(COLON)) return true;
    if (jj_scan_token(METHOD)) return true;
    return false;
  }

  static private boolean jj_3_8()
 {
    if (jj_scan_token(QUESTIONMARK)) return true;
    if (jj_3R_getAttribute_96_5_13()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public ParserHDDLTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static {
	   jj_la1_init_0();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[9];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public ParserHDDL(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public ParserHDDL(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new ParserHDDLTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 0; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public ParserHDDL(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new ParserHDDLTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new ParserHDDLTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public ParserHDDL(ParserHDDLTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserHDDLTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[29];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 0; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 29; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 9; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			   case 8: jj_3_9(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

   }
